# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.6
          channels: conda-forge

      - name: bootstrap
        run: ./scripts/bootstrap.sh

      - name: render chart
        run: /usr/share/miniconda/bin/python render.py > dist/layouts/partials/covid/combined.html
      
      - name: update website
        run: |
          if ! git diff --no-ext-diff --quiet --exit-code; then
            git config user.email "horace.guy.k@gmail.com"
            git config user.name "Horace Guy"
            git commit -am "update combined chart"
            git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
            git push origin master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
